image: nexus.engageska-portugal.pt/ska-docker/dspsr-build:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: dspsr
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2


stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - base_dir=${PWD}
    - ./bootstrap
    - mkdir install
    - echo "apsr bpsr cpsr2 caspsr mopsr sigproc dada" > backends.list
    - echo $CUDA_INCLUDE_DIR
    - echo $CUDA_LIB_DIR
    - ./configure --enable-shared --prefix=${base_dir}/install --with-cuda-include-dir=$CUDA_INCLUDE_DIR --with-cuda-lib-dir=$CUDA_LIB_DIR
    - make
    - make install
    # - curl -X POST -F token=${CI_JOB_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/${DSPSR_TEST_ID}/trigger/pipeline
  artifacts:
    paths:
      - install

test:
  stage: test
  script:
    - base_dir=${PWD}
    - ls ${base_dir}/install/
    - ls ${base_dir}/install/bin
    - ${base_dir}/install/bin/test_main ~[cuda][unit],~[cuda][no_file] -v high
    - curl -X POST -F token=${CI_JOB_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/${DSPSR_TEST_ID}/trigger/pipeline
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:stable
  script:
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
    - image=$DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_FOLDER/$IMAGE_NAME
    - version="2.0.0-$CI_COMMIT_SHORT_SHA"
    - docker build -t $image:$version .
    - docker tag $image:$version $image:latest
    - docker push $image:$version
    - docker push $image:latest
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "pipeline"
