stages:
  - build

build:
  stage: build
  tags:
    - dspsr-build
  script:
    - echo $LD_LIBRARY_FLAGS
    - echo $PATH
    - ./bootstrap
    - echo "apsr bpsr cpsr2 caspsr mopsr sigproc dada" > backends.list && ./configure --enable-shared
    - make
    - make install
