image: nexus.engageska-portugal.pt/ska-docker/dspsr-build:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: dspsr
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DSPSR_DIR: /home/psr/dspsr


stages:
  - build
  # - test
  - deploy

build:
  stage: build
  script:
    - echo "Using $(nproc) processers"
    - base_dir=${PWD}
    - ./bootstrap
    - echo "apsr bpsr cpsr2 caspsr mopsr sigproc dada" > backends.list
    - echo $CUDA_INCLUDE_DIR
    - echo $CUDA_LIB_DIR
    - mkdir -p ${DSPSR_DIR}/install
    - mkdir build && cd build
    - ./../configure --enable-shared --prefix=${DSPSR_DIR}/install --with-cuda-include-dir=$CUDA_INCLUDE_DIR --with-cuda-lib-dir=$CUDA_LIB_DIR
    - make -j$(nproc)
    - make install
    - cp -r ${DSPSR_DIR}/install/ ${base_dir}/install
    - curl -X POST -F token=${CI_JOB_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/${DSPSR_TEST_ID}/trigger/pipeline
  artifacts:
    paths:
      - install
      - test
  only:
    variables:
      - $CI_PIPELINE_SOURCE != "pipeline"
  tags:
    - ska
    - docker-executor

# test:
#   stage: test
#   script:
#     - base_dir=${PWD}
#     - mkdir -p ${DSPSR_DIR}
#     - cp -r ${base_dir}/install/ ${DSPSR_DIR}/install
#     - ${DSPSR_DIR}/install/bin/test_main ~[cuda][unit],~[cuda][no_file] -v high
#     - curl -X POST -F token=${CI_JOB_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/${DSPSR_TEST_ID}/trigger/pipeline
#   dependencies:
#     - build
#   only:
#     variables:
#       - $CI_PIPELINE_SOURCE != "pipeline"

deploy:
  stage: deploy
  image: docker:stable
  script:
    - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY_HOST
    - image=$DOCKER_REGISTRY_HOST/$DOCKER_REGISTRY_FOLDER/$IMAGE_NAME
    - version="2.0.0-$CI_COMMIT_SHORT_SHA"
    - docker build -t $image:$version . --build-arg MAKE_PROC=$(nproc)
    - docker tag $image:$version $image:latest
    - docker push $image:$version
    - docker push $image:latest
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "pipeline"
  # tags:
  #   - ska
  #   - docker-executor
