stages:
  - build

build:
  stage: build
  tags:
    - dspsr-build
  script:
    - echo $LD_LIBRARY_FLAGS
    - echo $PATH
    - ./bootstrap
    - ./configure --enable-shared
    - make
    - make install
