image: dshaff/dspsr-build:latest

stages:
  - build
  - test 

build:
  stage: build
  script:
    - ./bootstrap
    - mkdir build && cd build 
    - echo "apsr bpsr cpsr2 caspsr mopsr sigproc dada" > backends.list && ./../configure --enable-shared 
    - make
    - make install
  artifacts:
    paths: 
      - build/


test:
  stage: test 
  script: 
    - ./build/test/test_main
